// import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "@/app/globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* className={`${geistSans.variable} ${geistMono.variable} antialiased`} */}
      <body className={`${inter.className} antialiased`}>
        <main className="m-auto flex max-w-[600px] flex-col items-center pt-4">
          {children}
        </main>
      </body>
    </html>
  );
}
